export const countriesOptions = [
  { value: "USA", label: "USA", color: "#0052CC" },
  { value: "Spain", label: "Spain", color: "#0052CC" },
  { value: "Italy", label: "Italy", color: "#0052CC" },
  { value: "Germany", label: "Germany", color: "#0052CC" },
  { value: "China", label: "China", color: "#0052CC" },
  { value: "France", label: "France", color: "#0052CC" },
  { value: "Iran", label: "Iran", color: "#0052CC" },
  { value: "UK", label: "UK", color: "#0052CC" },
  { value: "Switzerland", label: "Switzerland", color: "#0052CC" },
  { value: "Turkey", label: "Turkey", color: "#0052CC" },
  { value: "Belgium", label: "Belgium", color: "#0052CC" },
  { value: "Netherlands", label: "Netherlands", color: "#0052CC" },
  { value: "Austria", label: "Austria", color: "#0052CC" },
  { value: "Canada", label: "Canada", color: "#0052CC" },
  { value: "S. Korea", label: "S. Korea", color: "#0052CC" },
  { value: "Portugal", label: "Portugal", color: "#0052CC" },
  { value: "Brazil", label: "Brazil", color: "#0052CC" },
  { value: "Israel", label: "Israel", color: "#0052CC" },
  { value: "Sweden", label: "Sweden", color: "#0052CC" },
  { value: "Australia", label: "Australia", color: "#0052CC" },
  { value: "Norway", label: "Norway", color: "#0052CC" },
  { value: "Russia", label: "Russia", color: "#0052CC" },
  { value: "Czechia", label: "Czechia", color: "#0052CC" },
  { value: "Ireland", label: "Ireland", color: "#0052CC" },
  { value: "Denmark", label: "Denmark", color: "#0052CC" },
  { value: "Chile", label: "Chile", color: "#0052CC" },
  { value: "Malaysia", label: "Malaysia", color: "#0052CC" },
  { value: "Romania", label: "Romania", color: "#0052CC" },
  { value: "Ecuador", label: "Ecuador", color: "#0052CC" },
  { value: "Poland", label: "Poland", color: "#0052CC" },
  { value: "Philippines", label: "Philippines", color: "#0052CC" },
  { value: "Japan", label: "Japan", color: "#0052CC" },
  { value: "India", label: "India", color: "#0052CC" },
  { value: "Luxembourg", label: "Luxembourg", color: "#0052CC" },
  { value: "Pakistan", label: "Pakistan", color: "#0052CC" },
  { value: "Indonesia", label: "Indonesia", color: "#0052CC" },
  { value: "Thailand", label: "Thailand", color: "#0052CC" },
  { value: "Saudi Arabia", label: "Saudi Arabia", color: "#0052CC" },
  { value: "Finland", label: "Finland", color: "#0052CC" },
  { value: "Greece", label: "Greece", color: "#0052CC" },
  { value: "Mexico", label: "Mexico", color: "#0052CC" },
  { value: "Panama", label: "Panama", color: "#0052CC" },
  { value: "South Africa", label: "South Africa", color: "#0052CC" },
  { value: "Peru", label: "Peru", color: "#0052CC" },
  {
    value: "Dominican Republic",
    label: "Dominican Republic",
    color: "#0052CC",
  },
  { value: "Iceland", label: "Iceland", color: "#0052CC" },
  { value: "Argentina", label: "Argentina", color: "#0052CC" },
  { value: "Serbia", label: "Serbia", color: "#0052CC" },
  { value: "Colombia", label: "Colombia", color: "#0052CC" },
  { value: "Singapore", label: "Singapore", color: "#0052CC" },
  { value: "Croatia", label: "Croatia", color: "#0052CC" },
  { value: "UAE", label: "UAE", color: "#0052CC" },
  { value: "Algeria", label: "Algeria", color: "#0052CC" },
  { value: "Estonia", label: "Estonia", color: "#0052CC" },
  { value: "Qatar", label: "Qatar", color: "#0052CC" },
  { value: "Ukraine", label: "Ukraine", color: "#0052CC" },
  { value: "Slovenia", label: "Slovenia", color: "#0052CC" },
  { value: "New Zealand", label: "New Zealand", color: "#0052CC" },
  { value: "Egypt", label: "Egypt", color: "#0052CC" },
  { value: "Hong Kong", label: "Hong Kong", color: "#0052CC" },
  { value: "Iraq", label: "Iraq", color: "#0052CC" },
  { value: "Armenia", label: "Armenia", color: "#0052CC" },
  { value: "Morocco", label: "Morocco", color: "#0052CC" },
  { value: "Diamond Princess", label: "Diamond Princess", color: "#0052CC" },
  { value: "Lithuania", label: "Lithuania", color: "#0052CC" },
  { value: "Bahrain", label: "Bahrain", color: "#0052CC" },
  { value: "Hungary", label: "Hungary", color: "#0052CC" },
  { value: "Bosnia", label: "Bosnia", color: "#0052CC" },
  { value: "Lebanon", label: "Lebanon", color: "#0052CC" },
  {
    value: "Moldova, Republic of",
    value: "label, Republic of",
    color: "#0052CC",
  },
  { value: "Latvia", label: "Latvia", color: "#0052CC" },
  { value: "Bulgaria", label: "Bulgaria", color: "#0052CC" },
  { value: "Kazakhstan", label: "Kazakhstan", color: "#0052CC" },
  { value: "Tunisia", label: "Tunisia", color: "#0052CC" },
  { value: "Slovakia", label: "Slovakia", color: "#0052CC" },
  { value: "Azerbaijan", label: "Azerbaijan", color: "#0052CC" },
  { value: "Andorra", label: "Andorra", color: "#0052CC" },
  { value: "Kuwait", label: "Kuwait", color: "#0052CC" },
  { value: "Costa Rica", label: "Costa Rica", color: "#0052CC" },
  { value: "Macedonia", label: "Macedonia", color: "#0052CC" },
  { value: "Uruguay", label: "Uruguay", color: "#0052CC" },
  { value: "Cyprus", label: "Cyprus", color: "#0052CC" },
  { value: "Belarus", label: "Belarus", color: "#0052CC" },
  { value: "Taiwan", label: "Taiwan", color: "#0052CC" },
  { value: "Réunion", label: "Réunion", color: "#0052CC" },
  { value: "Cameroon", label: "Cameroon", color: "#0052CC" },
  { value: "Albania", label: "Albania", color: "#0052CC" },
  { value: "Jordan", label: "Jordan", color: "#0052CC" },
  { value: "Burkina Faso", label: "Burkina Faso", color: "#0052CC" },
  { value: "Afghanistan", label: "Afghanistan", color: "#0052CC" },
  { value: "Oman", label: "Oman", color: "#0052CC" },
  { value: "San Marino", label: "San Marino", color: "#0052CC" },
  { value: "Vietnam", label: "Vietnam", color: "#0052CC" },
  { value: "Cuba", label: "Cuba", color: "#0052CC" },
  { value: "Honduras", label: "Honduras", color: "#0052CC" },
  { value: "Uzbekistan", label: "Uzbekistan", color: "#0052CC" },
  { value: "Channel Islands", label: "Channel Islands", color: "#0052CC" },
  { value: "Senegal", label: "Senegal", color: "#0052CC" },
  { value: "Ghana", label: "Ghana", color: "#0052CC" },
  { value: "Malta", label: "Malta", color: "#0052CC" },
  { value: "Côte d'Ivoire", values: "label d'Ivoire", color: "#0052CC" },
  { value: "Nigeria", label: "Nigeria", color: "#0052CC" },
  { value: "Faroe Islands", label: "Faroe Islands", color: "#0052CC" },
  {
    value: "Palestinian Territory, Occupied",
    label: "Territory, Occupied",
    color: "#0052CC",
  },
  { value: "Mauritius", label: "Mauritius", color: "#0052CC" },
  { value: "Montenegro", label: "Montenegro", color: "#0052CC" },
  { value: "Sri Lanka", label: "Sri Lanka", color: "#0052CC" },
  { value: "Georgia", label: "Georgia", color: "#0052CC" },
  { value: "Venezuela", label: "Venezuela", color: "#0052CC" },
  { value: "Martinique", label: "Martinique", color: "#0052CC" },
  { value: "DRC", label: "DRC", color: "#0052CC" },
  { value: "Brunei", label: "Brunei", color: "#0052CC" },
  { value: "Bolivia", label: "Bolivia", color: "#0052CC" },
  { value: "Kyrgyzstan", label: "Kyrgyzstan", color: "#0052CC" },
  { value: "Guadeloupe", label: "Guadeloupe", color: "#0052CC" },
  { value: "Mayotte", label: "Mayotte", color: "#0052CC" },
  { value: "Isle of Man", label: "Isle of Man", color: "#0052CC" },
  { value: "Cambodia", label: "Cambodia", color: "#0052CC" },
  { value: "Kenya", label: "Kenya", color: "#0052CC" },
  { value: "Niger", label: "Niger", color: "#0052CC" },
  {
    value: "Trinidad and Tobago",
    label: "Trinidad and Tobago",
    color: "#0052CC",
  },
  { value: "Paraguay", label: "Paraguay", color: "#0052CC" },
  { value: "Gibraltar", label: "Gibraltar", color: "#0052CC" },
  { value: "Rwanda", label: "Rwanda", color: "#0052CC" },
  { value: "Liechtenstein", label: "Liechtenstein", color: "#0052CC" },
  { value: "Bangladesh", label: "Bangladesh", color: "#0052CC" },
  { value: "Monaco", label: "Monaco", color: "#0052CC" },
  { value: "Aruba", label: "Aruba", color: "#0052CC" },
  { value: "Madagascar", label: "Madagascar", color: "#0052CC" },
  { value: "Guinea", label: "Guinea", color: "#0052CC" },
  { value: "French Guiana", label: "French Guiana", color: "#0052CC" },
  { value: "Djibouti", label: "Djibouti", color: "#0052CC" },
  { value: "Jamaica", label: "Jamaica", color: "#0052CC" },
  { value: "Guatemala", label: "Guatemala", color: "#0052CC" },
  { value: "El Salvador", label: "El Salvador", color: "#0052CC" },
  { value: "Barbados", label: "Barbados", color: "#0052CC" },
  { value: "Uganda", label: "Uganda", color: "#0052CC" },
  { value: "Macao", label: "Macao", color: "#0052CC" },
  { value: "Togo", label: "Togo", color: "#0052CC" },
  { value: "Zambia", label: "Zambia", color: "#0052CC" },
  { value: "French Polynesia", label: "French Polynesia", color: "#0052CC" },
  { value: "Mali", label: "Mali", color: "#0052CC" },
  { value: "Bermuda", label: "Bermuda", color: "#0052CC" },
  { value: "Ethiopia", label: "Ethiopia", color: "#0052CC" },
  { value: "Cayman Islands", label: "Cayman Islands", color: "#0052CC" },
  { value: "Bahamas", label: "Bahamas", color: "#0052CC" },
  { value: "Sint Maarten", label: "Sint Maarten", color: "#0052CC" },
  { value: "Congo", label: "Congo", color: "#0052CC" },
  { value: "Saint Martin", label: "Saint Martin", color: "#0052CC" },
  { value: "Eritrea", label: "Eritrea", color: "#0052CC" },
  { value: "Gabon", label: "Gabon", color: "#0052CC" },
  { value: "Myanmar", label: "Myanmar", color: "#0052CC" },
  {
    value: "Tanzania, United Republic of",
    label: "Tanzania",
    color: "#0052CC",
  },
  { value: "Guyana", label: "Guyana", color: "#0052CC" },
  { value: "Maldives", label: "Maldives", color: "#0052CC" },
  { value: "Haiti", label: "Haiti", color: "#0052CC" },
  { value: "New Caledonia", label: "New Caledonia", color: "#0052CC" },
  {
    value: "Syrian Arab Republic",
    label: "Syrian Arab Republic",
    color: "#0052CC",
  },
  { value: "Equatorial Guinea", label: "Equatorial Guinea", color: "#0052CC" },
  { value: "Mongolia", label: "Mongolia", color: "#0052CC" },
  { value: "Namibia", label: "Namibia", color: "#0052CC" },
  { value: "Benin", label: "Benin", color: "#0052CC" },
  { value: "Saint Lucia", label: "Saint Lucia", color: "#0052CC" },
  { value: "Dominica", label: "Dominica", color: "#0052CC" },
  { value: "Curaçao", label: "Curaçao", color: "#0052CC" },
  {
    value: "Libyan Arab Jamahiriya",
    label: "Libyan Arab Jamahiriya",
    color: "#0052CC",
  },
  { value: "Greenland", label: "Greenland", color: "#0052CC" },
  { value: "Grenada", label: "Grenada", color: "#0052CC" },
  {
    value: "Lao People's Democratic Republic",
    label: "Lao People's Democratic Republic",
    color: "#0052CC",
  },
  { value: "Mozambique", label: "Mozambique", color: "#0052CC" },
  { value: "Seychelles", label: "Seychelles", color: "#0052CC" },
  { value: "Suriname", label: "Suriname", color: "#0052CC" },
  { value: "MS Zaandam", label: "MS Zaandam", color: "#0052CC" },
  { value: "Zimbabwe", label: "Zimbabwe", color: "#0052CC" },
  {
    value: "Antigua and Barbuda",
    label: "Antigua and Barbuda",
    color: "#0052CC",
  },
  { value: "Guinea-Bissau", label: "Guinea-Bissau", color: "#0052CC" },
  {
    value: "Saint Kitts and Nevis",
    label: "Saint Kitts and Nevis",
    color: "#0052CC",
  },
  { value: "Swaziland", label: "Swaziland", color: "#0052CC" },
  { value: "Angola", label: "Angola", color: "#0052CC" },
  { value: "Sudan", label: "Sudan", color: "#0052CC" },
  {
    value: "Central African Republic",
    label: "Central African Republic",
    color: "#0052CC",
  },
  { value: "Chad", label: "Chad", color: "#0052CC" },
  { value: "Fiji", label: "Fiji", color: "#0052CC" },
  {
    value: "Holy See (Vatican City State)",
    label: "Holy See (Vatican City State)",
    color: "#0052CC",
  },
  { value: "Cabo Verde", label: "Cabo Verde", color: "#0052CC" },
  { value: "Mauritania", label: "Mauritania", color: "#0052CC" },
  { value: "Nepal", label: "Nepal", color: "#0052CC" },
  { value: "Liberia", label: "Liberia", color: "#0052CC" },
  { value: "St. Barth", label: "St. Barth", color: "#0052CC" },
  { value: "Nicaragua", label: "Nicaragua", color: "#0052CC" },
  { value: "Bhutan", label: "Bhutan", color: "#0052CC" },
  { value: "Montserrat", label: "Montserrat", color: "#0052CC" },
  { value: "Somalia", label: "Somalia", color: "#0052CC" },
  {
    value: "Turks and Caicos Islands",
    label: "Turks and Caicos Islands",
    color: "#0052CC",
  },
  { value: "Botswana", label: "Botswana", color: "#0052CC" },
  { value: "Gambia", label: "Gambia", color: "#0052CC" },
  { value: "Anguilla", label: "Anguilla", color: "#0052CC" },
  { value: "Belize", label: "Belize", color: "#0052CC" },
  {
    value: "British Virgin Islands",
    label: "British Virgin Islands",
    color: "#0052CC",
  },
  { value: "Burundi", label: "Burundi", color: "#0052CC" },
  { value: "Malawi", label: "Malawi", color: "#0052CC" },
  {
    value: "Caribbean Netherlands",
    label: "Caribbean Netherlands",
    color: "#0052CC",
  },
  {
    value: "Saint Vincent and the Grenadines",
    label: "Saint Vincent and the Grenadines",
    color: "#0052CC",
  },
  { value: "Sierra Leone", label: "Sierra Leone", color: "#0052CC" },
  { value: "Papua New Guinea", label: "Papua New Guinea", color: "#0052CC" },
  { value: "Timor-Leste", label: "Timor-Leste", color: "#0052CC" },
];

export const colourOptions = [
  { value: "ocean", label: "Ocean", color: "#00B8D9", isFixed: true },
  { value: "blue", label: "Blue", color: "#0052CC", isDisabled: true },
  { value: "purple", label: "Purple", color: "#5243AA" },
  { value: "red", label: "Red", color: "#FF5630", isFixed: true },
  { value: "orange", label: "Orange", color: "#FF8B00" },
  { value: "yellow", label: "Yellow", color: "#FFC400" },
  { value: "green", label: "Green", color: "#36B37E" },
  { value: "forest", label: "Forest", color: "#00875A" },
  { value: "slate", label: "Slate", color: "#253858" },
  { value: "silver", label: "Silver", color: "#666666" },
];

export const flavourOptions = [
  { value: "vanilla", label: "Vanilla", rating: "safe" },
  { value: "chocolate", label: "Chocolate", rating: "good" },
  { value: "strawberry", label: "Strawberry", rating: "wild" },
  { value: "salted-caramel", label: "Salted Caramel", rating: "crazy" },
];

export const stateOptions = [
  { value: "AL", label: "Alabama" },
  { value: "AK", label: "Alaska" },
  { value: "AS", label: "American Samoa" },
  { value: "AZ", label: "Arizona" },
  { value: "AR", label: "Arkansas" },
  { value: "CA", label: "California" },
  { value: "CO", label: "Colorado" },
  { value: "CT", label: "Connecticut" },
  { value: "DE", label: "Delaware" },
  { value: "DC", label: "District Of Columbia" },
  { value: "FM", label: "Federated States Of Micronesia" },
  { value: "FL", label: "Florida" },
  { value: "GA", label: "Georgia" },
  { value: "GU", label: "Guam" },
  { value: "HI", label: "Hawaii" },
  { value: "ID", label: "Idaho" },
  { value: "IL", label: "Illinois" },
  { value: "IN", label: "Indiana" },
  { value: "IA", label: "Iowa" },
  { value: "KS", label: "Kansas" },
  { value: "KY", label: "Kentucky" },
  { value: "LA", label: "Louisiana" },
  { value: "ME", label: "Maine" },
  { value: "MH", label: "Marshall Islands" },
  { value: "MD", label: "Maryland" },
  { value: "MA", label: "Massachusetts" },
  { value: "MI", label: "Michigan" },
  { value: "MN", label: "Minnesota" },
  { value: "MS", label: "Mississippi" },
  { value: "MO", label: "Missouri" },
  { value: "MT", label: "Montana" },
  { value: "NE", label: "Nebraska" },
  { value: "NV", label: "Nevada" },
  { value: "NH", label: "New Hampshire" },
  { value: "NJ", label: "New Jersey" },
  { value: "NM", label: "New Mexico" },
  { value: "NY", label: "New York" },
  { value: "NC", label: "North Carolina" },
  { value: "ND", label: "North Dakota" },
  { value: "MP", label: "Northern Mariana Islands" },
  { value: "OH", label: "Ohio" },
  { value: "OK", label: "Oklahoma" },
  { value: "OR", label: "Oregon" },
  { value: "PW", label: "Palau" },
  { value: "PA", label: "Pennsylvania" },
  { value: "PR", label: "Puerto Rico" },
  { value: "RI", label: "Rhode Island" },
  { value: "SC", label: "South Carolina" },
  { value: "SD", label: "South Dakota" },
  { value: "TN", label: "Tennessee" },
  { value: "TX", label: "Texas" },
  { value: "UT", label: "Utah" },
  { value: "VT", label: "Vermont" },
  { value: "VI", label: "Virgin Islands" },
  { value: "VA", label: "Virginia" },
  { value: "WA", label: "Washington" },
  { value: "WV", label: "West Virginia" },
  { value: "WI", label: "Wisconsin" },
  { value: "WY", label: "Wyoming" },
];

export const optionLength = [
  { value: 1, label: "general" },
  {
    value: 2,
    label:
      "Evil is the moment when I lack the strength to be true to the Good that compels me.",
  },
  {
    value: 3,
    label:
      "It is now an easy matter to spell out the ethic of a truth: 'Do all that you can to persevere in that which exceeds your perseverance. Persevere in the interruption. Seize in your being that which has seized and broken you.",
  },
];

export const dogOptions = [
  { id: 1, label: "Chihuahua" },
  { id: 2, label: "Bulldog" },
  { id: 3, label: "Dachshund" },
  { id: 4, label: "Akita" },
];

// let bigOptions = [];
// for (let i = 0; i < 10000; i++) {
// 	bigOptions = bigOptions.concat(colourOptions);
// }

export const groupedOptions = [
  {
    label: "Colours",
    options: colourOptions,
  },
  {
    label: "Flavours",
    options: flavourOptions,
  },
];
